tuple1 = int(input("Enter the lenght of the first tuple: "))
Tuple1 = tuple(range(tuple1))
print(Tuple1)
ind1 = int(input("Choose index number: "))
print("Chosen entry is: " + str(Tuple1[ind1]))
print("")

tuple2 = int(input("Enter the lenght of the second tuple: "))
Tuple2 = tuple(range(tuple2))
print(Tuple2)
ind2 = int(input("Choose index number: "))
print("Chosen entry is: " + str(Tuple2[ind2]))
print("")

tuple3 = int(input("Enter the lenght of the third tuple: "))
Tuple3 = tuple(range(tuple3))
print(Tuple3)
ind3 = int(input("Choose index number: "))
print("Chosen entry is: " + str(Tuple3[ind3]))
print("")

tuple4 = int(input("Enter the lenght of the forth tuple: "))
Tuple4 = tuple(range(tuple4))
print(Tuple4)
ind4 = int(input("Choose index number: "))
print("Chosen entry is: " + str(Tuple4[ind4]))
print("")
